# Evaluation

defaults:
  - config

hydra:
  run:
    dir: /home/robot/Desktop/attentin_shift/cliport # ${root_dir}

mode: val # val # 'val' or 'test'

# eval settings
agent: cliport_act # cliport_act
n_demos: 100 # 100 # number of val instances
train_demos: 50 # training demos used to train model
n_repeats: 1 # number of repeats
gpu: [0]
save_results: False # write results to json
update_results: False # False # overwrite existing json results?
checkpoint_type: val_missing # val_missing # val_missing  # 'last' #'val_missing' # test_best # 'val_missing'
val_on_heldout: True

disp: True # True # False
shared_memory: False
eval_task:     put-block-in-bowl-seen-colors-2arm # packing-boxes-pairs-seen-colors # put-block-in-bowl-seen-colors # packing-boxes-pairs-seen-colors #  # packing-color-shapes #packing-shapes # packing-seen-google-objects-group packing-boxes-pairs-seen-colors # task to evaluate the model on
model_task:    put-block-in-bowl-seen-colors-2arm # packing-boxes-pairs-seen-colors   # put-block-in-bowl-seen-colors # packing-boxes-pairs-seen-colors  # packing-same-color-shapes # packing-color-shapes  # packing-seen-google-objects-group packing-boxes-pairs-seen-colors # multi-language-conditioned # ${eval_task} # task the model was trained on (e.g. multi-language-conditioned or packing-boxes-pairs-seen-colors)
type: single # 'single' or 'multi'

# paths
model_dir: ${root_dir}
exp_folder: /home/robot/Desktop/attentin_shift/cliport/cliport_quickstart/packing-boxes-pairs-seen-colors-cliport-n1000-train/checkpoints/ # exps
data_dir: /home/robot/Desktop/attentin_shift/cliport/data # ${root_dir}/data
assets_root: /home/robot/Desktop/attentin_shift/cliport/environments/assets/ # ${root_dir}/cliport/environments/assets/
model_path: /home/robot/Desktop/attentin_shift/cliport/cliport_quickstart/multi-language-conditioned-cliport-n1000-train/checkpoints/ # E:\yyb\cliport-master\cliport_quickstart\cliport_quickstart\multi-language-conditioned-cliport-n1000-train\checkpoints/ # E:\yyb\cliport-master\data\packing-boxes-pairs-seen-colors-train/checkpoints/ # ${model_dir}/${exp_folder}/${model_task}-${agent}-n${train_demos}-train/checkpoints/ # path to pre-trained models
train_config: /home/robot/Desktop/attentin_shift/cliport/cfg/train.yaml # E:\yyb\cliport-master\cliport\.hydra/config.yaml # ${model_dir}/${exp_folder}/${model_task}-${agent}-n${train_demos}-train/.hydra/config.yaml # path to train config
save_path: home/robot/Desktop/attentin_shift/cliport/save model/packing-boxes-pairs-unseen-colors-cliport-n1000-train/save_checkpoints/ # ${model_dir}/${exp_folder}/${eval_task}-${agent}-n${train_demos}-train/checkpoints/ # path to save results
results_path: /home/robot/Desktop/attentin_shift/cliport/save model/packing-boxes-pairs-seen-colors-cliport-n1000-train/checkpoints/

# record videos (super slow)
record:
  save_video: True
  save_video_path: /home/robot/Desktop/attentin_shift/record_data/put-block-in-bowl-seen-colors/videos # ${model_dir}/${exp_folder}/${eval_task}-${agent}-n${train_demos}-train/videos/
  add_text: True
  fps: 20
  video_height: 640
  video_width: 720
